site_name: Cadwyn

# Repository settings
repo_name: Cadwyn
repo_url: https://github.com/zmievsa/cadwyn

plugins:
  - search
  - mkdocs-simple-hooks:
      hooks:
        on_pre_build: "docs.plugin:on_pre_build"

markdown_extensions:
  toc:
      permalink: true
  markdown.extensions.codehilite:
    guess_lang: false
  admonition: null
  codehilite: null
  extra: null
  pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format ''
  pymdownx.tabbed:
    alternate_style: true
  attr_list: null
  md_in_html: null
theme:
  name: 'material'
  features:
  - search.suggest
  - search.highlight
  - content.tabs.link
  - navigation.indexes
  - navigation.tracking
  - navigation.tabs
  - navigation.path
  - content.tooltips
  - content.code.annotate
  - content.code.copy
  - content.code.select
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - "Home":
    - "index.md"
    - "Contributing": "home/CONTRIBUTING.md"
    - "Changelog": "home/CHANGELOG.md"
  - "Quickstart": "quickstart.md"
  - "How to...": "how_to.md"
  - "Concepts":
    - "Mission": "concepts/mission.md"
    - "Methodology": "concepts/methodology.md"
    - "Service structure": "concepts/service_structure.md"
    - "Beware of data versioning": "concepts/beware_of_data_versioning.md"
    - "Main App": "concepts/main_app.md"
    - "CLI": "concepts/cli.md"
    - "Code generation": "concepts/code_generation.md"
    - "Version Changes": "concepts/version_changes.md"
    - "Endpoint migrations": "concepts/endpoint_migrations.md"
    - "Enum migrations": "concepts/enum_migrations.md"
    - "Schema migrations": "concepts/schema_migrations.md"
    - "Module migrations": "concepts/module_migrations.md"
    - "API Version header and context variables": "concepts/api_version_header_and_context_variables.md"

  - "Theory":
    - How we got here: "theory/how_we_got_here.md"
    - Literature: "theory/literature.md"
    - Design decisions: "theory/design_decisions.md"

watch:
- docs
- CHANGELOG.md
- mkdocs.yml
