name: CI
on:
  push:
    branches: [main]
    paths:
      - "**.py"
      - "**.toml"
      - "**.lock"
  pull_request:
    branches: [main]
    types: [opened, synchronize]
    paths:
      - "**.py"
      - "**.toml"
      - "**.lock"

jobs:
  Tests:
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ubuntu-latest
            python-version: "3.10"
          - os: ubuntu-latest
            python-version: "3.11"
          - os: windows-latest
            python-version: "3.10"
          - os: macos-latest
            python-version: "3.10"

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - run: poetry install --all-extras

      - name: Test
        run: make ci_supertest

  Lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          cache: 'poetry'

      - run: poetry install --all-extras

      - uses: pre-commit/action@v3.0.0

  Typecheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          cache: 'poetry'

      - run: |
          poetry install --all-extras
          echo "$(poetry env info --path)/bin" >> $GITHUB_PATH

      - uses: jakebailey/pyright-action@v1
        with:
          pylance-version: latest-release
