name: Release PYPI Package

on:
  release:
    types: [created]

jobs:
  Publish:
    name: Build & Publish distribution 📦 to PyPI 🐍
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    if: startsWith(github.ref, 'refs/tags/') # only publish to PyPI on tag pushes

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python-uv
      - run: uv build
      - run: uv publish
