name: Check Markdown links

on:
  schedule:
    # Run everyday at 9:00 AM
    - cron: "0 9 * * *"

jobs:
  build-docs-to-validate-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python-uv
      - run: tox run -e docs

  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: umbrelladocs/action-linkspector@v1
        with:
          reporter: github-check
          filter_mode: nofilter
          fail_level: any
