name: Check Markdown links

on:
  push:
    branches:
    - main
    - 3.x.x
    paths:
    - "**.md"
  pull_request:
      branches: [main, 3.x.x]
      types: [opened, synchronize]
      paths:
      - "**.md"
  schedule:
  # Run everyday at 9:00 AM
  - cron: "0 9 * * *"

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        folder-path: '.'
